name: publish to nuget
on:
  push:
    branches:
      - master
      - main
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: NuGet/setup-nuget@v1
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.100'

      - name: read common.props
        id: commonProps
        uses: juliangruber/read-file-action@v1
        with:
          path: ./common.props

      - name: get version
        id: getVersion
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: '(?<=>)[^<>]+(?=</Version>)'
          regex_flags: 'gim'
          search_string: '${{ steps.commonProps.outputs.content }}'

      - name: dotnet restore
        run: dotnet restore -s "https://api.nuget.org/v3/index.json"

      - name: dotnet build
        run: dotnet build -c Release
      
      - name: dotnet test
        run: dotnet test -c Release --no-restore --no-build

      - name: dotnet pack
        run: dotnet pack -c Release --no-build --property PackageOutputPath=${{ github.workspace }}/nugetPackages/

      - name: remove unused packages
        run: |
          cd ${{ github.workspace }}/nugetPackages
          shopt -s extglob
          rm -f !(Syrna.*)
          rm -f !(*.${{ steps.getVersion.outputs.first_match }}.nupkg)
          rm -f *.Blazor.Host.*
          rm -f *.Blazor.Server.Host.*
          rm -f *.Host.Shared.*
          rm -f *.HttpApi.Host.*
          rm -f *.IdentityServer.*
          rm -f *.AuthServer.*
          rm -f *.Web.Host.*
          rm -f *.Web.Unified.*
          rm -f *.HttpApi.Client.ConsoleTestApp.*
          rm -f *.Tests.*
          rm -f *.TestBase.*
          rm -f *.Demo.*
          ls

      - name: Push package to GitHub packages 
        if: needs.build.outputs.CommitsSinceVersionSource > 0 #Only release if there has been a commit/version change  
        run: dotnet nuget push ${{ github.workspace }}/nugetPackage/*.nupkg --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }}  --source "github"

      - name: dotnet nuget push to NuGet
        run: dotnet nuget push ${{ github.workspace }}/nugetPackages/*.nupkg -k ${{secrets.SYRNA_NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: determine if the tag exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: ${{ steps.getVersion.outputs.first_match }}
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_PACKAGE_TOKEN }}

      - name: add git tag
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.NUGET_PACKAGE_TOKEN }}
          tag: ${{ steps.getVersion.outputs.first_match }}
